Define PROJECT_NAME my-php-example

Define HOSTNAME php85
Define WORKSPACEFOLDER /app/${PROJECT_NAME}

<VirtualHost *:80>
	ServerName ${HOSTNAME}.localhost
  DocumentRoot ${WORKSPACEFOLDER}/public

	AllowEncodedSlashes on

  <Directory "${WORKSPACEFOLDER}/public">
    DirectoryIndex index.php index.html
    AllowOverride All
    Require all granted
  </Directory>

	<FilesMatch \.(html|php|tpl|twig)$>
    SetHandler "proxy:fcgi://${HOSTNAME}:9000"
	</FilesMatch>

</VirtualHost>
